name: chatr
description: Chat

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  data_connection_checker: ^0.3.4
  cloud_firestore: ^0.13.4+2
  firebase_core: ^0.4.4+3
  get_it: ^4.0.1
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  dartz: ^0.8.9
  shared_preferences: ^0.5.6+3
  cupertino_icons: ^0.1.2
  shortid: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: ^1.7.1
  json_serializable: ^3.2.2
  retrofit_generator: ^1.0.1

flutter:
  uses-material-design: true
